services:
  db:
    build: ./postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: default
    command: [ "-c", "log_statement=none", "-c", "log_min_messages=fatal" ]
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d default" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app

  postgraphile:
    build: ./postgraphile
    command:
      [
        "--connection",
        "postgresql://admin:admin@db:5432/default",
        "--owner-connection",
        "postgresql://admin:admin@db:5432/default",
        "--schema",
        "public",
        "--watch",
        "--enhance-graphiql",
        "--live",
        "--append-plugins",
        "@graphile/subscriptions-lds,@graphile-contrib/pg-simplify-inflector",
        "--allow-explain",
        "--dynamic-json",
        "--no-setof-functions-contain-nulls",
        "--enable-query-batching"
      ]
    ports:
      - 5000:5000
    networks:
      - app
    depends_on:
      db:
        condition: service_healthy

  wundergraph:
    build: ./wundergraph
    ports:
      - 9991:9991
    networks:
      - app
    depends_on:
      db:
        condition: service_healthy

networks:
  app:
    driver: bridge
